title: Hasan Rauf
#logo: 
description: Experienced Software Engineer with 8 years in development and testing. Skilled in Ruby, JavaScript, and PHP, with expertise in Agile methodologies. Proven record in ensuring application accessibility, security, and robustness. Holds an MS in IT and a background in Electrical Engineering.
show_downloads: true
theme: jekyll-theme-minimal